[project]
name = "mac-heater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "colorama>=0.4.6",
    "numpy>=2.0.2",
    "psutil>=6.1.0",
]
